# Generated by Django 3.1.4 on 2021-12-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='article_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='cartoon_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='destination',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='goods_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='item_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='order_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='qty_status',
            field=models.CharField(blank=True, choices=[('Piece', 'Piece'), ('Package', 'Package')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='shipment_chalan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sh_inline', to='Purchase.shipmentchalan'),
        ),
        migrations.AlterField(
            model_name='shipmentchalanitems',
            name='style_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
