# Generated by Django 2.2.14 on 2021-11-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryBuyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_email', models.CharField(max_length=200, null=True)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('address', models.TextField(null=True)),
                ('subcontract_party', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=0, max_length=200, null=True)),
                ('remark', models.TextField(null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCompAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200, null=True)),
                ('plot_no', models.CharField(max_length=20, null=True)),
                ('level_no', models.CharField(max_length=20, null=True)),
                ('road_no', models.CharField(max_length=20, null=True)),
                ('block_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('contact_person', models.CharField(max_length=200, null=True)),
                ('company_nature', models.CharField(max_length=200, null=True)),
                ('core_business', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('website', models.CharField(max_length=200, null=True)),
                ('province', models.CharField(max_length=120, null=True)),
                ('city', models.CharField(max_length=120, null=True)),
                ('zip_code', models.CharField(max_length=120, null=True)),
                ('trade_license_no', models.CharField(max_length=20, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCountryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Merchandise.LibraryCountry')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryCutOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_off', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryDealingMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_merchant_name', models.CharField(max_length=200)),
                ('d_merchant_address', models.TextField(blank=True, null=True)),
                ('d_merchant_phone', models.CharField(max_length=200)),
                ('d_merchant_email', models.EmailField(max_length=200)),
                ('d_merchant_company', models.CharField(blank=True, max_length=200, null=True)),
                ('d_merchant_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('d_merchant_dept', models.CharField(blank=True, max_length=200, null=True)),
                ('d_merchant_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryDesignSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_title', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryFactoryMerchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_merchant_name', models.CharField(max_length=200)),
                ('f_merchant_address', models.TextField(blank=True, null=True)),
                ('f_merchant_phone', models.CharField(max_length=200)),
                ('f_merchant_email', models.EmailField(max_length=200)),
                ('f_merchant_company', models.CharField(blank=True, max_length=200, null=True)),
                ('f_merchant_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('f_merchant_dept', models.CharField(blank=True, max_length=200, null=True)),
                ('f_merchant_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPacking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_title', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryPaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_term_title', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryProdDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200, null=True)),
                ('remark', models.TextField(null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryProdSubDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dept_name', models.CharField(max_length=200, null=True)),
                ('remark', models.TextField(null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryProductCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, null=True)),
                ('category_desc', models.TextField(null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryQualityLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_label_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibrarySeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryShipmentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_term_title', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryShipMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_mode_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryTeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.CharField(max_length=200)),
                ('leader_address', models.TextField(blank=True, null=True)),
                ('leader_phone', models.CharField(max_length=200)),
                ('leader_email', models.EmailField(max_length=200)),
                ('leader_company', models.CharField(blank=True, max_length=200, null=True)),
                ('leader_designation', models.CharField(blank=True, max_length=200, null=True)),
                ('leader_dept', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEntryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=40)),
                ('style_ref', models.CharField(max_length=120)),
                ('style_description', models.TextField()),
                ('repeat_job_no', models.CharField(max_length=120)),
                ('bh_merchant', models.CharField(max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('smv', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Order/')),
                ('file', models.FileField(blank=True, null=True, upload_to='Order/')),
                ('internal_ref', models.CharField(max_length=80)),
                ('copy_form', models.CharField(blank=True, max_length=80, null=True)),
                ('insert_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status_active', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=20, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_agent', to='Merchandise.LibraryAgent')),
                ('buyer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lib_buyer', to='Merchandise.LibraryBuyer')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_client', to='Merchandise.LibraryClient')),
                ('company_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='Merchandise.LibraryCompAddress')),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lib_company', to='Merchandise.LibraryCompany')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_currency', to='Merchandise.LibraryCurrency')),
                ('dealing_merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_dealing', to='Merchandise.LibraryDealingMerchant')),
                ('design_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_source', to='Merchandise.LibraryDesignSource')),
                ('factory_merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_factory', to='Merchandise.LibraryFactoryMerchant')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insert_by', to=settings.AUTH_USER_MODEL)),
                ('order_uom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_unit', to='Merchandise.LibraryUnit')),
                ('packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_packing', to='Merchandise.LibraryPacking')),
                ('product_cate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_product_cate', to='Merchandise.LibraryProductCate')),
                ('product_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_prod_dept', to='Merchandise.LibraryProdDept')),
                ('quality_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_quality', to='Merchandise.LibraryQualityLabel')),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_region', to='Merchandise.LibraryRegion')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_season', to='Merchandise.LibrarySeason')),
                ('ship_mode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ship_mode', to='Merchandise.LibraryShipMode')),
                ('shipment_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_term', to='Merchandise.LibraryShipmentTerm')),
                ('sub_dept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_sub_dept', to='Merchandise.LibraryProdSubDept')),
                ('team_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_leader', to='Merchandise.LibraryTeamLeader')),
                ('working_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_company', to='Merchandise.LibraryCompany')),
                ('working_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_location', to='Merchandise.LibraryCompAddress')),
            ],
        ),
        migrations.CreateModel(
            name='PoColorSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField()),
                ('country_shipment_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField()),
                ('tt_order_qty', models.IntegerField(default=0)),
                ('tt_rate', models.FloatField(default=0.0)),
                ('tt_amount', models.FloatField(default=0.0)),
                ('tt_excess_cut', models.FloatField(default=0.0)),
                ('tt_plan_cut_qty', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='Merchandise.LibraryCountry')),
                ('country_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countrytype_lib', to='Merchandise.LibraryCountryType')),
                ('cutoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_lib', to='Merchandise.LibraryCutOff')),
                ('packing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='Merchandise.LibraryPacking')),
                ('po_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_job_no', to='Merchandise.OrderEntryInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PO_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Projected', 'Projected')], max_length=20)),
                ('projected_po', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('po_no', models.CharField(max_length=120)),
                ('po_recieve_date', models.DateField(default=django.utils.timezone.now)),
                ('pub_shipment_date', models.DateField()),
                ('lead_time', models.CharField(blank=True, max_length=20, null=True)),
                ('org_shipment_date', models.DateField()),
                ('fac_recieve_date', models.DateField()),
                ('po_quantity', models.CharField(max_length=120)),
                ('avg_price', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('excess_cut_pct', models.FloatField(default=0.0)),
                ('plan_cut_qty', models.IntegerField(default=0)),
                ('status_active', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('tna_from_upto', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('internal_ref', models.CharField(max_length=120)),
                ('delay_for', models.CharField(blank=True, max_length=200, null=True)),
                ('file_no', models.CharField(max_length=200)),
                ('sc_or_lc', models.CharField(max_length=120)),
                ('file_add', models.FileField(blank=True, null=True, upload_to='Order/')),
                ('actual_po_no', models.ImageField(blank=True, null=True, upload_to='Order/')),
                ('remarks', models.TextField()),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_insert_by', to=settings.AUTH_USER_MODEL)),
                ('po_job_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='Merchandise.OrderEntryInfo')),
                ('po_packing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_packing', to='Merchandise.LibraryPacking')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=180, null=True)),
                ('product_code', models.CharField(blank=True, max_length=20, null=True)),
                ('item_group', models.CharField(blank=True, max_length=80, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=80, null=True)),
                ('vat_per_unit', models.CharField(blank=True, max_length=80, null=True)),
                ('rate_per_unit', models.CharField(blank=True, max_length=80, null=True)),
                ('current_stock', models.IntegerField(blank=True, default=0, null=True)),
                ('status_active', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_category', to='Merchandise.LibraryProductCate')),
            ],
        ),
        migrations.AddField(
            model_name='librarycompaddress',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compnay', to='Merchandise.LibraryCompany'),
        ),
        migrations.CreateModel(
            name='ColorSizeItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=120)),
                ('color', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=120)),
                ('order_qty', models.IntegerField(default=0)),
                ('rate', models.FloatField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('excess_cut', models.FloatField(default=0)),
                ('plan_cut_qty', models.IntegerField(default=0)),
                ('status_active', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
                ('gmt_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Merchandise.LibraryProduct')),
                ('po_color_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_size', to='Merchandise.PoColorSize')),
            ],
        ),
    ]
