# Generated by Django 2.2.14 on 2021-11-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocolorsize',
            name='po_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_no', to='Merchandise.PO_Details'),
        ),
    ]
