# Generated by Django 2.2.14 on 2021-11-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0002_auto_20211121_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMVDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_set_ratio', models.FloatField(default=0)),
                ('tt_sew_smv', models.FloatField(default=0)),
                ('tt_cut_smv', models.FloatField(default=0)),
                ('tt_fin_smv', models.FloatField(default=0)),
                ('gt_tt_smv', models.FloatField(default=0)),
                ('created_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('smv_job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smv_job', to='Merchandise.OrderEntryInfo')),
            ],
        ),
        migrations.CreateModel(
            name='SmvItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_ratio', models.FloatField(default=0)),
                ('sew_smv_pcs', models.FloatField(default=0)),
                ('cut_smv_pcs', models.FloatField(default=0)),
                ('fin_smv_pcs', models.FloatField(default=0)),
                ('complexity', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('print', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('print_days', models.IntegerField(blank=True, default=0, null=True)),
                ('embro', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('embro_days', models.IntegerField(blank=True, default=0, null=True)),
                ('wash', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('wash_days', models.IntegerField(blank=True, default=0, null=True)),
                ('sp_work', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('sp_work_days', models.IntegerField(blank=True, default=0, null=True)),
                ('gmts_dyeing', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('gmts_dyeing_days', models.IntegerField(blank=True, default=0, null=True)),
                ('aop', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('aop_days', models.IntegerField(blank=True, default=0, null=True)),
                ('tt_smv', models.FloatField(default=0)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smv_products', to='Merchandise.LibraryProduct')),
                ('smv_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smv_items', to='Merchandise.SMVDetails')),
            ],
        ),
    ]
