# Generated by Django 2.2.14 on 2021-11-21 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0003_smvdetails_smvitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentryinfo',
            name='sub_dept_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_agent', to='Merchandise.LibraryAgent'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='bh_merchant',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_client', to='Merchandise.LibraryClient'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_currency', to='Merchandise.LibraryCurrency'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='dealing_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_dealing', to='Merchandise.LibraryDealingMerchant'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='factory_merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_factory', to='Merchandise.LibraryFactoryMerchant'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='internal_ref',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='order_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_unit', to='Merchandise.LibraryUnit'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_packing', to='Merchandise.LibraryPacking'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='product_cate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_product_cate', to='Merchandise.LibraryProductCate'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='product_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_prod_dept', to='Merchandise.LibraryProdDept'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='quality_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_quality', to='Merchandise.LibraryQualityLabel'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_region', to='Merchandise.LibraryRegion'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='repeat_job_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_season', to='Merchandise.LibrarySeason'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='ship_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ship_mode', to='Merchandise.LibraryShipMode'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='shipment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_term', to='Merchandise.LibraryShipmentTerm'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='style_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='style_ref',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='sub_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_sub_dept', to='Merchandise.LibraryProdSubDept'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_leader', to='Merchandise.LibraryTeamLeader'),
        ),
    ]
