# Generated by Django 3.1.4 on 2021-11-22 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0004_auto_20211121_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smvitems',
            old_name='print',
            new_name='smv_print',
        ),
        migrations.RemoveField(
            model_name='smvitems',
            name='smv_details',
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='tt_cut_smv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='tt_fin_smv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='tt_set_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderentryinfo',
            name='tt_sew_smv',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='smvitems',
            name='order_smv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_smv', to='Merchandise.orderentryinfo'),
        ),
        migrations.DeleteModel(
            name='SMVDetails',
        ),
    ]
