# Generated by Django 3.1.4 on 2021-11-23 12:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0005_auto_20211122_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_details',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='Merchandise.librarycountry'),
        ),
        migrations.AddField(
            model_name='po_details',
            name='country_shipment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='country_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='countrytype_lib', to='Merchandise.librarycountrytype'),
        ),
        migrations.AddField(
            model_name='po_details',
            name='cutoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutoff_lib', to='Merchandise.librarycutoff'),
        ),
        migrations.AddField(
            model_name='po_details',
            name='cutoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packing', to='Merchandise.librarypacking'),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='po_color_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_size', to='Merchandise.po_details'),
        ),
        migrations.DeleteModel(
            name='PoColorSize',
        ),
    ]
