# Generated by Django 3.1.4 on 2021-11-23 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0006_auto_20211123_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizeitems',
            name='po_color_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_size', to='Merchandise.po_details'),
        ),
    ]
