# Generated by Django 3.1.4 on 2021-11-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0007_auto_20211123_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizeitems',
            name='article_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='color',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='gmt_items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Merchandise.libraryproduct'),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='size',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='status_active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
