# Generated by Django 3.1.4 on 2021-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0008_auto_20211123_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizeitems',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='excess_cut',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='order_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
