# Generated by Django 3.1.4 on 2021-11-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0009_auto_20211123_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_details',
            name='color_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colorsizeitems',
            name='plan_cut_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
