# Generated by Django 3.2.8 on 2021-11-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0010_auto_20211123_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_details',
            name='plan_cut_qty',
            field=models.FloatField(default=0),
        ),
    ]
