# Generated by Django 3.2.8 on 2021-11-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0011_alter_po_details_plan_cut_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorsizeitems',
            name='plan_cut_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
