# Generated by Django 2.2.14 on 2021-12-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0012_alter_colorsizeitems_plan_cut_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smvitems',
            name='cut_smv_pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='fin_smv_pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smv_products', to='Merchandise.LibraryProduct'),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='set_ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='sew_smv_pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
