# Generated by Django 3.1.4 on 2021-12-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0013_auto_20211205_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_details',
            name='fac_recieve_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='file_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='internal_ref',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='org_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='projected_po',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='sc_or_lc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='tna_from_upto',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
