# Generated by Django 3.1.4 on 2021-12-08 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0014_auto_20211207_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderentryinfo',
            name='buyer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_buyer', to='Merchandise.librarybuyer'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='company_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='Merchandise.librarycompaddress'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_company', to='Merchandise.librarycompany'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='tt_cut_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='tt_fin_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='tt_set_ratio',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='tt_sew_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='working_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_company', to='Merchandise.librarycompany'),
        ),
        migrations.AlterField(
            model_name='orderentryinfo',
            name='working_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_location', to='Merchandise.librarycompaddress'),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='avg_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='excess_cut_pct',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='order_status',
            field=models.CharField(blank=True, choices=[('Confirmed', 'Confirmed'), ('Projected', 'Projected')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='plan_cut_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='po_job_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entry', to='Merchandise.orderentryinfo'),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='po_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='po_packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_packing', to='Merchandise.librarypacking'),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='po_quantity',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='po_recieve_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='pub_shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='po_details',
            name='status_active',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='aop',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='complexity',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='embro',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='gmts_dyeing',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='smv_print',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='sp_work',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='tt_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='wash',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
    ]
