# Generated by Django 2.2.14 on 2021-12-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0015_auto_20211208_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentryinfo',
            name='g_tt_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='aop_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='embro_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='gmts_dyeing_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='print_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='sp_work_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='tt_smv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='smvitems',
            name='wash_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
