# Generated by Django 2.2.14 on 2021-12-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0016_auto_20211209_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_details',
            name='amt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='exc',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='order_quan',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='plan_cut',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='tt_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
