# Generated by Django 3.1.4 on 2021-12-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0017_auto_20211209_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smvitems',
            name='tt_smv',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
