# Generated by Django 3.1.4 on 2021-12-26 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0018_auto_20211213_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderentryinfo',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_term', to='Merchandise.librarypaymentterm'),
        ),
    ]
