# Generated by Django 2.2.14 on 2022-01-03 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0019_orderentryinfo_payment_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryFabrication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabrication', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='po_details',
            name='gsm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='colorsizeitems',
            name='fabrication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_fabrication', to='Merchandise.LibraryFabrication'),
        ),
    ]
