# Generated by Django 3.1.4 on 2022-01-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0020_auto_20220103_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po_details',
            name='projected_po',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=20, null=True),
        ),
    ]
