# Generated by Django 3.2.8 on 2022-01-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0020_auto_20220103_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycompany',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
