# Generated by Django 3.2.8 on 2022-01-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0021_librarycompany_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='po_details',
            name='an',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='c',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='po_details',
            name='s',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
