# Generated by Django 2.2.14 on 2022-01-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0021_auto_20220106_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycompany',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
