# Generated by Django 3.1.4 on 2022-01-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0023_librarybodypart_librarybodyparttype_librarycolorsizesensitive_librarycolortype_libraryconsumptionbas'),
        ('Merchandise', '0022_auto_20220124_2125'),
    ]

    operations = [
    ]
