# Generated by Django 3.1.4 on 2022-02-01 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0023_librarybodypart_librarybodyparttype_librarycolorsizesensitive_librarycolortype_libraryconsumptionbas'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPreCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
                ('quotation_id', models.CharField(blank=True, max_length=120, null=True)),
                ('style_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('style_desc', models.CharField(blank=True, max_length=220, null=True)),
                ('Buyer_name', models.CharField(blank=True, max_length=120, null=True)),
                ('prod_dept', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, max_length=120, null=True)),
                ('er', models.CharField(blank=True, max_length=120, null=True)),
                ('agent', models.CharField(blank=True, max_length=120, null=True)),
                ('job_qty', models.CharField(blank=True, max_length=120, null=True)),
                ('order_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('item_details', models.CharField(blank=True, max_length=250, null=True)),
                ('costing_date', models.DateField(blank=True, null=True)),
                ('incoterm', models.CharField(blank=True, max_length=250, null=True)),
                ('incoterm_place', models.CharField(blank=True, max_length=250, null=True)),
                ('machine_line', models.CharField(blank=True, max_length=120, null=True)),
                ('prod_line', models.CharField(blank=True, max_length=120, null=True)),
                ('costing_per', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('sew_smv', models.FloatField(blank=True, default=0, null=True)),
                ('sew_efficiency', models.FloatField(blank=True, default=0, null=True)),
                ('cut_smv', models.FloatField(blank=True, default=0, null=True)),
                ('cut_efficiency', models.FloatField(blank=True, default=0, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('budget_minute', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Budget/Image')),
                ('file_no', models.CharField(blank=True, max_length=120, null=True)),
                ('internal_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('copy_form', models.CharField(blank=True, max_length=120, null=True)),
                ('redy_to_approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('mini_marker_upload', models.FileField(blank=True, null=True, upload_to='Budget/Image')),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bjob_no', to='Merchandise.orderentryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='YarnCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('comp_one', models.CharField(blank=True, max_length=120, null=True)),
                ('pct', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('type', models.CharField(blank=True, max_length=120, null=True)),
                ('cons_qty', models.FloatField(blank=True, default=0, null=True)),
                ('tt_cons_qty', models.FloatField(blank=True, default=0, null=True)),
                ('supplier', models.CharField(blank=True, max_length=120, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('b_job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ybudget_cost', to='Merchandise.budgetprecost')),
            ],
        ),
        migrations.CreateModel(
            name='FabricCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fbudget_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fab_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Inline_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('gms', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_grey_cons', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('total_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('body_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_body_part', to='Merchandise.librarybodypart')),
                ('body_part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_bp_type', to='Merchandise.librarybodyparttype')),
                ('color_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ctype', to='Merchandise.librarycolortype')),
                ('con_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_con_basis', to='Merchandise.libraryconsumptionbasis')),
                ('cs_sensitive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_cs_sensitive', to='Merchandise.librarycolorsizesensitive')),
                ('fab_nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_fn', to='Merchandise.libraryfabnature')),
                ('fabric_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_inline', to='Merchandise.fabriccost')),
                ('fabric_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_fsource', to='Merchandise.libraryfabricsource')),
                ('gmts_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fab_items', to='Merchandise.libraryproduct')),
                ('nom_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_nsupplier', to='Merchandise.librarynominatedsupp')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_uom', to='Merchandise.libraryunit')),
                ('width_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_dia_type', to='Merchandise.librarydiatypes')),
            ],
        ),
        migrations.CreateModel(
            name='ConversionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbudget_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='con_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion_Inline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fab_desc', models.CharField(blank=True, max_length=120, null=True)),
                ('process', models.CharField(blank=True, max_length=120, null=True)),
                ('process_loss', models.FloatField(blank=True, default=0, null=True)),
                ('reg_qty', models.FloatField(blank=True, default=0, null=True)),
                ('avg_reg_qty', models.FloatField(blank=True, default=0, null=True)),
                ('charge_unit', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True)),
                ('conversion_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conver_inline', to='Merchandise.conversioncost')),
            ],
        ),
    ]
