# Generated by Django 3.1.4 on 2022-01-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0024_merge_20220131_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po_details',
            name='an',
        ),
        migrations.RemoveField(
            model_name='po_details',
            name='c',
        ),
        migrations.RemoveField(
            model_name='po_details',
            name='s',
        ),
        migrations.AlterField(
            model_name='librarycompany',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
