# Generated by Django 3.1.4 on 2022-02-03 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0024_budgetprecost_conversion_inline_conversioncost_fabric_inline_item_fabriccost_yarncost'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryYarnSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryYarnType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='budgetprecost',
            old_name='cut_smv',
            new_name='avg_rate',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='Buyer_name',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='company',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='incoterm',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='prod_dept',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='region',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='sew_smv',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='style_desc',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='style_ref',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='color',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='comp_one',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='cons_qty',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='count',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='pct',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='yarncost',
            name='type',
        ),
        migrations.AddField(
            model_name='budgetprecost',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='budgetprecost',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpc_insert_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='yarncost',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='yarncost',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yarn_insert_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetprecost',
            name='job_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_cost', to='Merchandise.orderentryinfo'),
        ),
        migrations.AlterField(
            model_name='budgetprecost',
            name='job_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='conversioncost',
            name='b_job_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_cost', to='Merchandise.budgetprecost'),
        ),
        migrations.AlterField(
            model_name='fabriccost',
            name='b_job_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_cost', to='Merchandise.budgetprecost'),
        ),
        migrations.AlterField(
            model_name='yarncost',
            name='b_job_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yarn_cost', to='Merchandise.budgetprecost'),
        ),
        migrations.CreateModel(
            name='Yarn_Inline_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('comp_one', models.CharField(blank=True, max_length=120, null=True)),
                ('pct', models.CharField(blank=True, max_length=120, null=True)),
                ('color', models.CharField(blank=True, max_length=120, null=True)),
                ('cons_qty', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ysupplier', to='Merchandise.libraryyarnsupplier')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_yarn_type', to='Merchandise.libraryyarntype')),
                ('yarn_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yarn_inline', to='Merchandise.yarncost')),
            ],
        ),
    ]
