# Generated by Django 3.2.8 on 2022-02-01 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0025_auto_20220131_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetPreCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(blank=True, max_length=120, null=True)),
                ('prod_dept', models.CharField(blank=True, max_length=120, null=True)),
                ('currency', models.CharField(blank=True, max_length=120, null=True)),
                ('er', models.CharField(blank=True, max_length=120, null=True)),
                ('agent', models.CharField(blank=True, max_length=120, null=True)),
                ('job_qty', models.FloatField(blank=True, default=0, null=True)),
                ('avg_rate', models.FloatField(blank=True, default=0, null=True)),
                ('order_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('item_details', models.CharField(blank=True, max_length=250, null=True)),
                ('costing_date', models.DateField(blank=True, null=True)),
                ('incoterm', models.CharField(blank=True, max_length=250, null=True)),
                ('incoterm_place', models.CharField(blank=True, max_length=250, null=True)),
                ('machine_line', models.CharField(blank=True, max_length=120, null=True)),
                ('prod_line', models.CharField(blank=True, max_length=120, null=True)),
                ('costing_per', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('sew_smv', models.FloatField(blank=True, default=0, null=True)),
                ('sew_efficiency', models.FloatField(blank=True, default=0, null=True)),
                ('cut_smv', models.FloatField(blank=True, default=0, null=True)),
                ('cut_efficiency', models.FloatField(blank=True, default=0, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('budget_minute', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Budget/Image')),
                ('file_no', models.CharField(blank=True, max_length=120, null=True)),
                ('internal_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('copy_form', models.CharField(blank=True, max_length=120, null=True)),
                ('redy_to_approved', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True)),
                ('mini_marker_upload', models.FileField(blank=True, null=True, upload_to='Budget/Image')),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpc_insert_by', to=settings.AUTH_USER_MODEL)),
                ('job_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='border_entry', to='Merchandise.orderentryinfo')),
            ],
        ),
    ]
