# Generated by Django 3.1.4 on 2022-02-05 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0025_auto_20220203_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
