# Generated by Django 3.2.8 on 2022-02-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0026_budgetprecost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprecost',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='prod_dept',
        ),
    ]
