# Generated by Django 3.1.4 on 2022-02-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0026_libraryprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversioncost',
            name='tt_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='conversioncost',
            name='tt_avg_reg_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='conversioncost',
            name='tt_charge_unit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='conversioncost',
            name='tt_reg_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fabric_inline_item',
            name='source',
            field=models.CharField(blank=True, choices=[('Foreign', 'Foreign'), ('Local', 'Local')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='librarybodypart',
            name='bp_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conversion_inline',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_cprocess', to='Merchandise.libraryprocess'),
        ),
        migrations.AlterField(
            model_name='conversion_inline',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fabric_inline_item',
            name='body_part',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fabric_inline_item',
            name='body_part_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
