# Generated by Django 3.1.4 on 2022-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0027_auto_20220206_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryfabricdescription',
            name='gsm_weight',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='libraryfabricdescription',
            name='yarn_one_pct',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='libraryfabricdescription',
            name='yarn_two_pct',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
