# Generated by Django 3.2.8 on 2022-02-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0027_auto_20220201_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprecost',
            name='incoterm',
        ),
    ]
