# Generated by Django 3.2.8 on 2022-02-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0028_remove_budgetprecost_incoterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprecost',
            name='cut_smv',
        ),
        migrations.RemoveField(
            model_name='budgetprecost',
            name='sew_smv',
        ),
    ]
