# Generated by Django 3.1.4 on 2022-02-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0028_auto_20220207_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric_inline_item',
            name='gmts_items',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
