# Generated by Django 3.2.8 on 2022-02-01 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0029_auto_20220201_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprecost',
            name='image',
        ),
    ]
