# Generated by Django 3.1.4 on 2022-02-10 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0030_grey_cons_grey_cons_items_librarypcsqty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorContrast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_contrast', to='Merchandise.budgetprecost')),
                ('fabric_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fab_cost', to='Merchandise.fabric_inline_item')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrast', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='yarn_inline_item',
            name='count',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='yarn_inline_item',
            name='pct',
            field=models.FloatField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='yarn_inline_item',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='ColorContrastItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmts_color', models.CharField(blank=True, max_length=200, null=True)),
                ('contrast_color', models.CharField(blank=True, max_length=200, null=True)),
                ('color_contrast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrast_item', to='Merchandise.colorcontrast')),
            ],
        ),
    ]
