# Generated by Django 3.2.8 on 2022-02-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0030_remove_budgetprecost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprecost',
            name='region',
        ),
    ]
