# Generated by Django 3.2.8 on 2022-02-01 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0031_remove_budgetprecost_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetprecost',
            name='job_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='border_entry', to='Merchandise.orderentryinfo'),
        ),
    ]
