# Generated by Django 3.1.4 on 2022-02-02 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0032_alter_budgetprecost_job_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fbudget_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fab_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Inline_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('gms', models.CharField(blank=True, max_length=80, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('avg_grey_cons', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('total_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('total_amount', models.FloatField(blank=True, default=0, null=True)),
                ('body_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_body_part', to='Merchandise.librarybodypart')),
                ('body_part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_bp_type', to='Merchandise.librarybodyparttype')),
                ('color_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_ctype', to='Merchandise.librarycolortype')),
                ('con_basis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_con_basis', to='Merchandise.libraryconsumptionbasis')),
                ('cs_sensitive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_cs_sensitive', to='Merchandise.librarycolorsizesensitive')),
                ('fab_nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_fn', to='Merchandise.libraryfabnature')),
                ('fabric_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabric_inline', to='Merchandise.fabriccost')),
                ('fabric_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_fsource', to='Merchandise.libraryfabricsource')),
                ('gmts_items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fab_items', to='Merchandise.libraryproduct')),
                ('nom_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_nsupplier', to='Merchandise.librarynominatedsupp')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_uom', to='Merchandise.libraryunit')),
                ('width_dia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_dia_type', to='Merchandise.librarydiatypes')),
            ],
        ),
    ]
