# Generated by Django 3.1.4 on 2022-02-12 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0032_auto_20220212_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryDyeing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('const_and_comp', models.CharField(max_length=200, null=True)),
                ('process_type', models.CharField(max_length=200, null=True)),
                ('process_name', models.CharField(max_length=200, null=True)),
                ('color', models.CharField(max_length=200, null=True)),
                ('width_dia_type', models.CharField(max_length=200, null=True)),
                ('inhouse_rate', models.FloatField(default=0)),
                ('bdt_to_usd', models.FloatField(default=0)),
                ('uom', models.CharField(max_length=80, null=True)),
                ('rate_type', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryKnitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, null=True)),
                ('body_part', models.CharField(max_length=200, null=True)),
                ('const_and_comp', models.CharField(max_length=200, null=True)),
                ('gsm', models.PositiveIntegerField(default=0)),
                ('yarn_desc', models.CharField(max_length=200, null=True)),
                ('uom', models.CharField(max_length=80, null=True)),
                ('inhouse_rate', models.FloatField(default=0)),
                ('bdt_to_usd', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
