# Generated by Django 3.1.4 on 2022-02-17 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0033_librarydyeing_libraryknitting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care_Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('tt_ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('grand_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('sub_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_qty_dzn', models.FloatField(blank=True, default=0, null=True)),
                ('grand_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_pcs', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('avg_ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('avg_grand_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('avg_sub_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_qty_dzn', models.FloatField(blank=True, default=0, null=True)),
                ('avg_grand_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_pcs', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_level', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DyeingColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('tt_charge', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_charge', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_popup', to='Merchandise.budgetprecost')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryDoller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.FloatField(default=0)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryGroupsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_item_name', models.CharField(max_length=200, null=True)),
                ('group_item_uom', models.CharField(max_length=80, null=True)),
                ('trims_type', models.CharField(max_length=80, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryTrimSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrimCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_cons_unit', models.FloatField(blank=True, default=0, null=True)),
                ('tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('tt_sub_amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_grand_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('tt_grand_amount', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trim_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trim_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='conversion_inline',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='grey_cons_items',
            name='item_sizes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TrimCostItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('brand_sup_ref', models.CharField(blank=True, max_length=200, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('nominated_supp', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_uom', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_unit_gmts', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_qty', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amt', models.FloatField(blank=True, default=0, null=True)),
                ('apvt_req', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Budget/Image')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lib_tsource', to='Merchandise.librarytrimsource')),
                ('trim_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trim_items', to='Merchandise.trimcost')),
            ],
        ),
        migrations.CreateModel(
            name='DyeingColorItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmts_color', models.CharField(blank=True, max_length=200, null=True)),
                ('fabric_color', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_rate', models.FloatField(blank=True, default=0, null=True)),
                ('charge_unit', models.FloatField(blank=True, default=0, null=True)),
                ('dyeing_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dyeing_item', to='Merchandise.dyeingcolor')),
            ],
        ),
        migrations.AddField(
            model_name='dyeingcolor',
            name='conversion_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='con_cost', to='Merchandise.conversion_inline'),
        ),
        migrations.AddField(
            model_name='dyeingcolor',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_pop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Care_level_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('gmts_item', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('gmts_size', models.CharField(blank=True, max_length=200, null=True)),
                ('item_color', models.CharField(blank=True, max_length=200, null=True)),
                ('item_sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('cons', models.FloatField(blank=True, default=0, null=True)),
                ('ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('tt_qty', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('placement', models.FloatField(blank=True, default=0, null=True)),
                ('pcs', models.FloatField(blank=True, default=0, null=True)),
                ('care_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='care_items', to='Merchandise.care_level')),
                ('color_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cl_colorsize', to='Merchandise.colorsizeitems')),
            ],
        ),
        migrations.AddField(
            model_name='care_level',
            name='trim_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctrim_cost', to='Merchandise.trimcostitems'),
        ),
    ]
