# Generated by Django 3.1.4 on 2022-02-20 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0034_auto_20220217_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbConsCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('avg_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embcons_level', to='Merchandise.budgetprecost')),
            ],
        ),
        migrations.CreateModel(
            name='EmbellishmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embl_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embl_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEmbCostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryEmbCostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emb_cost_name', to='Merchandise.libraryembcostname')),
            ],
        ),
        migrations.CreateModel(
            name='EmbellishmentCostItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(blank=True, max_length=200, null=True)),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('body_part', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('emb_supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_dzn', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True)),
                ('embellishment_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embl_items', to='Merchandise.embellishmentcost')),
            ],
        ),
        migrations.CreateModel(
            name='EmbConsCosting_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('gmts_item', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=200, null=True)),
                ('gmts_size', models.CharField(blank=True, max_length=200, null=True)),
                ('cons', models.FloatField(blank=True, default=0, null=True)),
                ('ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('color_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emb_colorsize', to='Merchandise.colorsizeitems')),
                ('emb_cons_costing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embcons_items', to='Merchandise.embconscosting')),
            ],
        ),
        migrations.AddField(
            model_name='embconscosting',
            name='embl_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='embcons_cost', to='Merchandise.embellishmentcostitem'),
        ),
        migrations.AddField(
            model_name='embconscosting',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embcons_insert_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
