# Generated by Django 3.2.8 on 2022-02-08 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0034_libraryyarnsupplier_libraryyarntype_yarn_inline_item_yarncost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grey_Cons_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchandise.budgetprecost')),
                ('color_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchandise.colorsizeitems')),
                ('fabric_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchandise.fabric_inline_item')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
