# Generated by Django 3.2.8 on 2022-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0035_grey_cons_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='grey_cons_items',
            name='seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
