# Generated by Django 3.1.4 on 2022-02-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0035_auto_20220220_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryWash_CostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_cost_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WashConsCosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_tt_ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('w_grand_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('w_sub_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('w_grand_tt_qty', models.FloatField(blank=True, default=0, null=True)),
                ('w_grand_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_grand_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_sub_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_grand_tt_qty', models.FloatField(blank=True, default=0, null=True)),
                ('w_avg_grand_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washcons_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wc_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WashCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tt_rate', models.FloatField(blank=True, default=0, null=True)),
                ('tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('insert_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wash_cost', to='Merchandise.budgetprecost')),
                ('inserted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wash_insert_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WashCost_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_type', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('cons_dzn', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.FloatField(blank=True, default=0, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True)),
                ('wash_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wash_items', to='Merchandise.washcost')),
            ],
        ),
        migrations.CreateModel(
            name='WashConsCosting_Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_po_no', models.CharField(blank=True, max_length=200, null=True)),
                ('w_country', models.CharField(blank=True, max_length=200, null=True)),
                ('w_gmts_item', models.CharField(blank=True, max_length=200, null=True)),
                ('w_color', models.CharField(blank=True, max_length=200, null=True)),
                ('w_gmts_size', models.CharField(blank=True, max_length=200, null=True)),
                ('w_item_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('w_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_ex_pct', models.FloatField(blank=True, default=0, null=True)),
                ('w_tt_cons', models.FloatField(blank=True, default=0, null=True)),
                ('w_rate', models.FloatField(blank=True, default=0, null=True)),
                ('w_amount', models.FloatField(blank=True, default=0, null=True)),
                ('w_tt_qty', models.FloatField(blank=True, default=0, null=True)),
                ('w_tt_amount', models.FloatField(blank=True, default=0, null=True)),
                ('w_pcs', models.FloatField(blank=True, default=0, null=True)),
                ('color_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wc_colorsize', to='Merchandise.colorsizeitems')),
                ('wash_cons_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wcons_items', to='Merchandise.washconscosting')),
            ],
        ),
        migrations.AddField(
            model_name='washconscosting',
            name='wash_cost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washcons_cost', to='Merchandise.washcost_items'),
        ),
        migrations.CreateModel(
            name='LibraryWash_CostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('w_cost_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wash_cname', to='Merchandise.librarywash_costname')),
            ],
        ),
    ]
