# Generated by Django 3.2.8 on 2022-02-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0036_grey_cons_items_seq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grey_cons_items',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='grey_cons_items',
            name='fabric_cost',
        ),
        migrations.RemoveField(
            model_name='grey_cons_items',
            name='seq',
        ),
        migrations.CreateModel(
            name='Grey_Cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_job_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grey_cons', to='Merchandise.budgetprecost')),
                ('fabric_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Merchandise.fabric_inline_item')),
            ],
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='grey_cons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grey_items', to='Merchandise.grey_cons'),
        ),
    ]
