# Generated by Django 3.2.8 on 2022-02-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Merchandise', '0037_auto_20220209_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='grey_cons',
            name='avg_finish_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='avg_grey_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='avg_pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='avg_process_loss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='avg_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='gt_avg_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='gt_tt_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='inserted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grey_insert_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='sub_avg_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='sub_avg_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='sub_tt_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='sub_tt_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='tt_finish_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='tt_grey_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='tt_pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='tt_process_loss',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons',
            name='tt_rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='dia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='fab_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='gmts_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='insert_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='item_sizes',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='pcs',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='po_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='process_loss_pct',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grey_cons_items',
            name='total_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grey_cons_items',
            name='grey_cons',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
