# Generated by Django 3.2.8 on 2022-02-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0038_auto_20220210_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='grey_cons_items',
            name='grey_cons_unit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grey_cons_items',
            name='grey_cons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grey_items', to='Merchandise.grey_cons'),
        ),
    ]
