# Generated by Django 3.2.8 on 2022-02-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Merchandise', '0039_auto_20220210_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grey_cons_items',
            name='insert_date',
        ),
        migrations.RemoveField(
            model_name='grey_cons_items',
            name='inserted_by',
        ),
    ]
